name: lint & test

on:
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: macos-12
    steps:
      - name: Lint
      - uses: actions/checkout@v2
        run: swiftlint

  test:
    runs-on: macos-12
    steps:
      - name: Test
      - uses: actions/checkout@v2
        run: swift test -v
