name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: macOS-latest

  test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: swift test -v
